#!/usr/bin/env node
/* eslint-disable no-console */
/**
 * Figma Export Script (Hybrid: MCP Sync + REST API)
 *
 * Exports component screenshots from Figma using the Figma REST API.
 * Component mappings are loaded from figma-components.json (generated by figma:sync).
 * Falls back to hardcoded mappings if JSON file doesn't exist.
 *
 * Requires FIGMA_ACCESS_TOKEN environment variable.
 */

import * as fs from 'node:fs/promises';
import * as path from 'node:path';

interface FigmaComponent {
  name: string;
  nodeId: string;
  fileKey: string;
}

interface FigmaVariant {
  name: string;
  nodeId: string;
  storybookName: string;
}

interface ComponentData {
  componentName: string;
  frameNodeId: string;
  variants: FigmaVariant[];
}

interface SyncResult {
  timestamp: string;
  fileKey: string;
  components: ComponentData[];
}

/**
 * Fallback component mapping (used if figma-components.json doesn't exist)
 * Run `pnpm figma:sync` to generate mappings automatically via MCP
 */
const FALLBACK_FIGMA_COMPONENTS: Record<string, FigmaComponent> = {
  // Property Panels
  'NodePropertiesPanel-Default': {
    name: 'Node Properties Panel',
    nodeId: '1-1', // Replace with actual Figma node IDs or run figma:sync
    fileKey: process.env.FIGMA_FILE_KEY || '',
  },
  'EdgePropertiesPanel-Default': {
    name: 'Edge Properties Panel',
    nodeId: '1-2',
    fileKey: process.env.FIGMA_FILE_KEY || '',
  },
  'SectionPropertiesPanel-Default': {
    name: 'Section Properties Panel',
    nodeId: '1-3',
    fileKey: process.env.FIGMA_FILE_KEY || '',
  },
  'TextPropertiesPanel-Default': {
    name: 'Text Properties Panel',
    nodeId: '1-4',
    fileKey: process.env.FIGMA_FILE_KEY || '',
  },
  'ResourcePropertiesPanel-Default': {
    name: 'Resource Properties Panel',
    nodeId: '1-5',
    fileKey: process.env.FIGMA_FILE_KEY || '',
  },

  // Interactive Components
  'ContextMenu-Default': {
    name: 'Context Menu',
    nodeId: '2-1',
    fileKey: process.env.FIGMA_FILE_KEY || '',
  },
  'ToolbarButton-Default': {
    name: 'Toolbar Button',
    nodeId: '2-2',
    fileKey: process.env.FIGMA_FILE_KEY || '',
  },
  'EditorButton-Default': {
    name: 'Editor Button',
    nodeId: '2-3',
    fileKey: process.env.FIGMA_FILE_KEY || '',
  },

  // AI Features
  'RoadmapAiModal-Default': {
    name: 'AI Modal',
    nodeId: '3-1',
    fileKey: process.env.FIGMA_FILE_KEY || '',
  },
};

/**
 * Load component mappings from figma-components.json (MCP-generated)
 * Falls back to hardcoded mappings if file doesn't exist
 */
async function loadComponentMappings(): Promise<Record<string, FigmaComponent>> {
  const mappingPath = path.join(process.cwd(), 'scripts/figma-components.json');

  try {
    await fs.access(mappingPath);
    const content = await fs.readFile(mappingPath, 'utf-8');
    const syncResult: SyncResult = JSON.parse(content);

    // Flatten variants from all components
    const allVariants: FigmaVariant[] = [];
    for (const component of syncResult.components) {
      allVariants.push(...component.variants);
    }

    console.log(`📋 Loaded ${allVariants.length} variants from figma-components.json`);
    console.log(`   (Synced at: ${new Date(syncResult.timestamp).toLocaleString()})`);
    console.log(`   Components: ${syncResult.components.length}\n`);

    const components: Record<string, FigmaComponent> = {};
    for (const variant of allVariants) {
      components[variant.storybookName] = {
        name: variant.name,
        nodeId: variant.nodeId,
        fileKey: syncResult.fileKey,
      };
    }

    return components;
  } catch {
    console.log('⚠️  No figma-components.json found, using fallback mappings');
    console.log('   Run `pnpm figma:sync` to generate mappings automatically\n');
    return FALLBACK_FIGMA_COMPONENTS;
  }
}

interface FigmaImageResponse {
  err: string | null;
  images: Record<string, string>;
}

async function exportFigmaImage(
  fileKey: string,
  nodeId: string,
  outputPath: string,
): Promise<void> {
  const token = process.env.FIGMA_ACCESS_TOKEN;
  if (!token) {
    throw new Error('FIGMA_ACCESS_TOKEN environment variable is required');
  }

  // Get image URL from Figma API
  const imageUrl = `https://api.figma.com/v1/images/${fileKey}?ids=${nodeId}&format=png&scale=1`;
  const response = await fetch(imageUrl, {
    headers: {
      'X-Figma-Token': token,
    },
  });

  if (!response.ok) {
    throw new Error(`Figma API error: ${response.status} ${response.statusText}`);
  }

  const data = (await response.json()) as FigmaImageResponse;

  if (data.err) {
    throw new Error(`Figma API error: ${data.err}`);
  }

  const imageDownloadUrl = data.images[nodeId];
  if (!imageDownloadUrl) {
    throw new Error(`No image URL returned for node ${nodeId}`);
  }

  // Download image
  const imageResponse = await fetch(imageDownloadUrl);
  if (!imageResponse.ok) {
    throw new Error(`Failed to download image: ${imageResponse.statusText}`);
  }

  const buffer = await imageResponse.arrayBuffer();
  await fs.writeFile(outputPath, Buffer.from(buffer));

  console.log(`✓ Exported: ${path.basename(outputPath)}`);
}

async function main() {
  const outputDir = path.join(process.cwd(), 'visual-tests/figma');

  // Ensure output directory exists
  await fs.mkdir(outputDir, { recursive: true });

  const fileKey = process.env.FIGMA_FILE_KEY;
  if (!fileKey) {
    console.error('❌ FIGMA_FILE_KEY environment variable is required');
    console.log('\nSet it in your .env file or export it:');
    console.log('  export FIGMA_FILE_KEY=your-file-key');
    console.log('\nExtract from Figma URL: https://figma.com/design/FILE_KEY/...');
    process.exit(1);
  }

  console.log('🎨 Exporting Figma components...\n');

  // Load component mappings (MCP-generated or fallback)
  const FIGMA_COMPONENTS = await loadComponentMappings();

  let exported = 0;
  let skipped = 0;

  for (const [storybookName, component] of Object.entries(FIGMA_COMPONENTS)) {
    try {
      if (!component.nodeId || component.nodeId === '1-1' || component.nodeId === 'PLACEHOLDER') {
        console.log(`⚠ Skipped: ${storybookName} (no Figma node ID configured)`);
        skipped++;
        continue;
      }

      const outputPath = path.join(outputDir, `${storybookName}.png`);
      await exportFigmaImage(fileKey, component.nodeId, outputPath);
      exported++;
    } catch (error) {
      console.error(`✗ Failed to export ${storybookName}:`, error);
    }
  }

  console.log(`\n✅ Exported ${exported} images`);
  if (skipped > 0) {
    console.log(`⚠️  Skipped ${skipped} images`);
    console.log('   Run `pnpm figma:sync` to generate node IDs automatically');
  }
}

main().catch((error) => {
  console.error('❌ Export failed:', error);
  process.exit(1);
});
